package com.zm.skill.controller.dto;

public enum ErrorCode {
    SOURCE_UNREACHABLE, PARSE_FAILED, AI_TIMEOUT, VALIDATION_FAILED,
    DUPLICATE_DETECTED, REVIEW_REQUIRED, UNSUPPORTED_FORMAT, FILE_TOO_LARGE,
    BATCH_LIMIT_EXCEEDED, IDEMPOTENCY_CONFLICT, INVALID_URL, NOT_FOUND, INTERNAL_ERROR
}
